//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NID.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DiasporaEntities : DbContext
    {
        public DiasporaEntities()
            : base("name=DiasporaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<get_migration_skills_Result> get_migration_skills(Nullable<int> agr1, string arg2)
        {
            var agr1Parameter = agr1.HasValue ?
                new ObjectParameter("agr1", agr1) :
                new ObjectParameter("agr1", typeof(int));
    
            var arg2Parameter = arg2 != null ?
                new ObjectParameter("arg2", arg2) :
                new ObjectParameter("arg2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_migration_skills_Result>("get_migration_skills", agr1Parameter, arg2Parameter);
        }
    
        public virtual ObjectResult<get_government_Result> get_government(Nullable<int> agr1, string arg2)
        {
            var agr1Parameter = agr1.HasValue ?
                new ObjectParameter("agr1", agr1) :
                new ObjectParameter("agr1", typeof(int));
    
            var arg2Parameter = arg2 != null ?
                new ObjectParameter("arg2", arg2) :
                new ObjectParameter("arg2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_government_Result>("get_government", agr1Parameter, arg2Parameter);
        }
    
        public virtual ObjectResult<get_remittance_Result> get_remittance(string level, string tyear, Nullable<int> from, Nullable<int> to, string arg2)
        {
            var levelParameter = level != null ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(string));
    
            var tyearParameter = tyear != null ?
                new ObjectParameter("tyear", tyear) :
                new ObjectParameter("tyear", typeof(string));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(int));
    
            var arg2Parameter = arg2 != null ?
                new ObjectParameter("arg2", arg2) :
                new ObjectParameter("arg2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_remittance_Result>("get_remittance", levelParameter, tyearParameter, fromParameter, toParameter, arg2Parameter);
        }
    }
}
