//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NID.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ElectionEntities : DbContext
    {
        public ElectionEntities()
            : base("name=ElectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<field_metadata> field_metadata { get; set; }
    
        public virtual ObjectResult<get_constituency_Result> get_constituency(string assembly)
        {
            var assemblyParameter = assembly != null ?
                new ObjectParameter("assembly", assembly) :
                new ObjectParameter("assembly", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_constituency_Result>("get_constituency", assemblyParameter);
        }
    
        public virtual ObjectResult<get_voters_Result> get_voters(Nullable<System.DateTime> dated, string assembly, Nullable<int> constituency)
        {
            var datedParameter = dated.HasValue ?
                new ObjectParameter("dated", dated) :
                new ObjectParameter("dated", typeof(System.DateTime));
    
            var assemblyParameter = assembly != null ?
                new ObjectParameter("assembly", assembly) :
                new ObjectParameter("assembly", typeof(string));
    
            var constituencyParameter = constituency.HasValue ?
                new ObjectParameter("constituency", constituency) :
                new ObjectParameter("constituency", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_voters_Result>("get_voters", datedParameter, assemblyParameter, constituencyParameter);
        }
    
        public virtual ObjectResult<get_candidate_votes_Result> get_candidate_votes(string type, Nullable<int> year, string assembly, Nullable<int> constituency)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var assemblyParameter = assembly != null ?
                new ObjectParameter("assembly", assembly) :
                new ObjectParameter("assembly", typeof(string));
    
            var constituencyParameter = constituency.HasValue ?
                new ObjectParameter("constituency", constituency) :
                new ObjectParameter("constituency", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_candidate_votes_Result>("get_candidate_votes", typeParameter, yearParameter, assemblyParameter, constituencyParameter);
        }
    
        public virtual ObjectResult<get_polling_stations_Result> get_polling_stations(Nullable<int> year, string election, string assembly, string seat)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var electionParameter = election != null ?
                new ObjectParameter("election", election) :
                new ObjectParameter("election", typeof(string));
    
            var assemblyParameter = assembly != null ?
                new ObjectParameter("assembly", assembly) :
                new ObjectParameter("assembly", typeof(string));
    
            var seatParameter = seat != null ?
                new ObjectParameter("seat", seat) :
                new ObjectParameter("seat", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_polling_stations_Result>("get_polling_stations", yearParameter, electionParameter, assemblyParameter, seatParameter);
        }
    
        public virtual ObjectResult<get_polling_scheme_Result> get_polling_scheme(Nullable<int> year, string election, string assembly, string seat, Nullable<int> sr)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var electionParameter = election != null ?
                new ObjectParameter("election", election) :
                new ObjectParameter("election", typeof(string));
    
            var assemblyParameter = assembly != null ?
                new ObjectParameter("assembly", assembly) :
                new ObjectParameter("assembly", typeof(string));
    
            var seatParameter = seat != null ?
                new ObjectParameter("seat", seat) :
                new ObjectParameter("seat", typeof(string));
    
            var srParameter = sr.HasValue ?
                new ObjectParameter("sr", sr) :
                new ObjectParameter("sr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_polling_scheme_Result>("get_polling_scheme", yearParameter, electionParameter, assemblyParameter, seatParameter, srParameter);
        }
    }
}
