//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NID.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_metadata
    {
        public long id { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string display_label { get; set; }
        public string placeholder { get; set; }
        public string tooltip { get; set; }
        public Nullable<int> section_number { get; set; }
        public string section_name { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string sql_type { get; set; }
        public string input_type { get; set; }
        public Nullable<bool> is_required { get; set; }
        public Nullable<int> min_length { get; set; }
        public Nullable<int> max_length { get; set; }
        public Nullable<decimal> min_value { get; set; }
        public Nullable<decimal> max_value { get; set; }
        public Nullable<int> decimal_places { get; set; }
        public string regex_pattern { get; set; }
        public Nullable<bool> is_readonly { get; set; }
        public Nullable<bool> is_computed { get; set; }
        public string computed_expression { get; set; }
        public string default_value { get; set; }
        public string default_expression { get; set; }
        public Nullable<bool> is_foreign_key { get; set; }
        public string dropdown_source_table { get; set; }
        public string dropdown_value_column { get; set; }
        public string dropdown_text_column { get; set; }
        public string dropdown_where { get; set; }
        public string dropdown_order_by { get; set; }
        public string dependent_on_column { get; set; }
        public string dependent_on_table { get; set; }
        public Nullable<bool> is_multi_select { get; set; }
        public Nullable<bool> include_blank_option { get; set; }
        public string custom_query { get; set; }
        public Nullable<bool> allow_insert { get; set; }
        public Nullable<bool> allow_update { get; set; }
        public Nullable<bool> show_in_list { get; set; }
        public Nullable<bool> is_searchable { get; set; }
        public Nullable<bool> is_sortable { get; set; }
        public Nullable<bool> exportable { get; set; }
        public Nullable<bool> importable { get; set; }
        public Nullable<bool> show_in_mobile { get; set; }
        public string roles_visible { get; set; }
        public string roles_editable { get; set; }
        public Nullable<bool> audit_log { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> is_deleted { get; set; }
    }
}
